server:
  port: 8181
chucknorris:
  url: https://api.chucknorris.io/jokes/random
springdoc:
  swagger-ui:
    enabled: true
# http://localhost:8181/swagger-ui/index.html 
# http://localhost:8181/v3/api-docs.yaml 
# https://docs.swagger.io/swagger-core/v2.0.0-RC3/apidocs/io/swagger/v3/oas/annotations/Operation.html
spring:
  datasource:
    url: jdbc:hsqldb:mem:mydb
    username: sa
    password: sa

