server:
  port: 8443
  ssl:
    key-store: classpath:keystore.p12
    key-store-type: PKCS12
    key-alias: mysslcert
chucknorris:
  url: https://api.chucknorris.io/jokes/random
springdoc:
  swagger-ui:
    enabled: true
# https://localhost:8443/swagger-ui/index.html 
# https://localhost:8443/v3/api-docs.yaml 
# https://docs.swagger.io/swagger-core/v2.0.0-RC3/apidocs/io/swagger/v3/oas/annotations/Operation.html
spring:
  datasource:
    url: jdbc:hsqldb:mem:mydb
    username: sa
    password: sa

